export const HANDLE_ADD_USER_MODAL = 'HANDLE_ADD_USER_MODAL';
export const ADD_USER = 'ADD_USER';
export const SET_SELECTED_PEOPLE = 'SET_SELECTED_PEOPLE'
export const REMOVE_USER = 'REMOVE_USER';
export const CHECK_ALL_PEOPLE = 'CHECK_ALL_PEOPLE';
export const CHECK_PEOPLE = 'CHECK_PEOPLE';
export const DELETE_SELECTED_PEOPLE = 'DELETE_SELECTED_PEOPLE';
