export const HANDLE_ADD_USER_MODAL = 'HANDLE_ADD_USER_MODAL';
export const ADD_USER = 'ADD_USER';
export const SET_SELECTED_PEOPLE = 'SET_SELECTED_PEOPLE'
export const REMOVE_USER = 'REMOVE_USER';
export const SELECT_USERS = 'SELECT_USERS';
